language: java
jdk:
  - oraclejdk11
  - openjdk10
  - oraclejdk9
  - oraclejdk8
  - openjdk7
before_install: .travis/before_install.sh
script: mvn verify
after_success: .travis/after_success.sh
branches:
  only:
  - master
  - /^next\/.*$/
env:
  global:
  - secure: htnYzp+cwnjg16EIjlwuHAgmvuZsppHDVTcYiCfZwbs4hftw8OuU8uPBGOWrz2ESb9h5Loh+ohj0GivTKLOJBhbaYBMbIt8O0i7AJBJ8z9mj++zAzGUKiUZocXVN167vLK+2QIey5hp1qxc+zvsS8jaH2zavw+PKFlhMpv1U2Nk=
  - secure: YcEadcDvwKlJJE5ETba+LWmqWTZ/vDfYRa2Ru8dn+2tigOsGHbZu+m3q7jn11rmN0wHSy+0lSL4usp7l+Ei1kXNjvm13+GTvSBpAuga6/kY3c50R1Xr4UQ3GuaLCGsJ9wnEp4OZ4FXRucY2yDN+FTd5ZTD/nl8T63gthqXchR+o=
